language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

env:
  global:
    # Doctr deploy key for NSLS-II/arvpyf
    - secure: "ZS5GLJvTOkKhpnTCrAa6lwu/yYS7XRUmsGzl4o8Wgor5E/9rFoCZPEJXy6hCohuZwc42SJi6FyVKnSkoyjkeSvtAIFxpgykaT1wh0uj2uKQUoqM/4wPIaV5+LlUv44M1e9tIJ8BNQ+QO+252AShVqFS6Cx/sRRxsTd7Hxx8EFMq1Iua20aiP/JdAKvYo1A/IvT5L+aGA53MxBg/MJgQ/1rRPxI2QPeuXDt06jWQ7EIJdoaG8XT+ww6Gg5eCxVY8eEm1MiuWJIjbuPwp67lJtm7qmDjZGAwjF7hzpXg9iyCvgOMU0FkWbozbifmosbOLdCyY9wrtFhSqnZ+3qQaSWJruwJ+K0DTK6MADOS62cAb2GvnAwcFbwkQ5m/xnwbcfqgw5yiN9lt0OIJsNpvplX5hIX99GCwMmdNkRb3/5SlbIKroIjBvkrPTl83sUOBmklkJx1C9x0EjZlWF+bZlJux0XwujrFBwp6Tx60tSrVacW7DGSTJQkVfJbUiiqNhcKcfD4+Sw+aZcoKhzEZFVi/kqUmz2BHii1/Cd6zfAsmnq6vNC7LH9Z3m0BNXmRtv3c1r3Iy6l6St2Ag7/fd8chfsFp45MFTw2C4lsURQlr/khdvp1TM1kB79rfUFzpwCfu1BUAyZ1Sxtp2hvB7/831T5bfj7Br2SnuDuhmDVuC9ilY="

install:
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

script:
  - coverage run -m pytest  # Run the tests 
  - flake8 --max-line-length=115  # Enforce code style (but relax line length limit a bit).
  - set -e # If any of the following steps fail, just stop at that point.
  - make -C docs html  # Build the documentation.
  - pip install doctr
  - doctr deploy --built-docs docs/build/html .  # Publish the documentation.